pkg/pool/pool.go
Using neofs-api-go client.New to create grpc connections.
Added parsing uri scheme.
=> [#9] Dropped direct gRPC connections

pkg/pool/pool.go
=> [#12] Implemented client.Object in Pool

pkg/pool/sampler_test.go
=> [#14] Added tests for sampler

pkg/pool/pool.go, pkg/pool/sampler_test.go
=> [#15] Added healthy node rebalance

pkg/pool/pool.go
Closes #19 
Also addded function polling is container created or not.
=> [#19] Implement client.Container interface in pool

pkg/pool/pool.go
Forgot to add WaitFotContainerPresence to  Pool Interface
=> Add WaitFotContainerPresence to Pool Interface

.gitignore, go.mod, go.sum
Closes #24 
Updated api-go version
Also fixed missing vendor in gitignore (I'm not sure I makes sense to create a separate PR for that)
=> Update api go

pkg/pool/pool.go, pkg/pool/sampler_test.go
=> [#28] Add recreating session token

pool/pool.go, pool/pool_test.go
=> [#32] Require at least one healthy node

policy/json.go, policy/json_test.go, policy/query_test.go
=> policy: remove `netmap/v2` dependency

session/container.go, session/container_test.go, session/session.go, session/session_test.go, session/test/container.go, session/test/token.go, session/xheader.go, session/xheader_test.go, util/signature/data.go, util/signature/options.go, util/signature/util.go
=> Move xheader, session and util from neofs-api-go

reputation/peer.go, reputation/peer_test.go, reputation/test/generate.go, reputation/trust.go, reputation/trust_test.go
=> Move reputation package from neofs-api-go

checksum/test/generate.go, object/address.go, object/address_test.go, object/attribute.go, object/attribute_test.go, object/error.go, object/error_test.go, object/fmt.go, object/fmt_test.go, object/id.go, object/id_test.go, object/object.go, object/range.go, object/range_test.go, object/raw.go, object/raw_test.go, object/rw.go, object/search.go, object/search_test.go, object/splitid.go, object/splitid_test.go, object/splitinfo.go, object/splitinfo_test.go, object/test/generate.go, object/tombstone.go, object/tombstone_test.go, object/type.go, object/type_test.go, object/wellknown_attributes.go, signature/test/generate.go
=> Move object package from neofs-api-go

netmap/selector.go
=> netmap: fix typo in comment

netmap/node_info.go
=> netmap: remove deprecated methods

audit/result.go, audit/result_test.go, audit/test/generate.go, version/test/generate.go
=> Move audit package from neofs-api-go

storagegroup/storagegroup.go, storagegroup/storagegroup_test.go, storagegroup/test/generate.go
=> Move storagegroup package from neofs-api-go

eacl/enums.go, eacl/enums_test.go, eacl/filter.go, eacl/filter_test.go, eacl/record.go, eacl/record_test.go, eacl/table.go, eacl/table_test.go, eacl/target.go, eacl/target_test.go, eacl/test/generate.go
Close #58 .
Moved to the top-level.
=> Move eacl package from neofs-api-go

container/announcement.go, container/announcement_test.go, container/attribute.go, container/attribute_test.go, container/container.go, container/container_test.go, container/opts.go, container/test/generate.go, container/wellknown_attributes.go, netmap/test/generate.go, session/container.go, session/session.go
=> Move container package from neofs-api-go

token/bearer.go, token/bearer_test.go, token/test/generate.go
=> Move token package from neofs-api-go

go.mod, go.sum, pool/cache.go, pool/pool.go, pool/pool_test.go, pool/sampler_test.go
closes #38 
related to https://github.com/nspcc-dev/neofs-http-gw/issues/95
=> [#38] Add session token cache

client/container.go
Relates to https://github.com/nspcc-dev/neofs-node/issues/804.
=> client: Do not change eACL version in `SetEACL`

owner/id.go, owner/id_test.go, owner/test/id.go
Close nspcc-dev/neofs-api-go#352 .
=> owner: check id for validity

subnet/subnet.go, subnet/subnet_test.go
=> subnet: Add methods to check subnet owner and ID

netmap/helper_test.go, netmap/policy.go, netmap/policy_test.go, netmap/selector.go, netmap/subnet.go, netmap/subnet_test.go
=> netmap: process subnet in selection

pool/mock_test.go, pool/pool.go, pool/pool_test.go, pool/sampler_test.go
=> [#74] Add priority to nodes

pool/pool.go
Default session token is created for object service requests and should not be reused in container or any other service requests.
Closes #101
=> pool: Ignore default session token in non object service requests

pool/pool.go
For clients which want to provide NeoFS internal balance information.
Ignored request retry, because it does not use session tokens to perform the operation.
=> pool: Add balance command

client/opts.go, go.mod, go.sum
Related to https://github.com/nspcc-dev/neofs-api-go/pull/366
Default values should be okay for most of the cases.
=> client: Provide RWTimeout option

acl/types.go, acl/types_test.go, container/container.go, container/opts.go
=> [#106] Add basic acl parser

pool/pool.go, pool/pool_test.go
=> [#118] Use correct owner in session token

README.md
=> [#99] docs: add README.md

pool/pool.go
=> [#142] Drop retry for container operations

owner/convert_test.go, owner/id.go, owner/id_test.go
=> owner: add helpers for working with script hash

client/object_get.go, client/object_search.go
=> client: Fix server stream reading

client/client.go, client/container.go, client/errors.go, client/object_delete.go, client/object_get.go, client/object_hash.go, client/object_put.go, client/object_search.go, client/status/container.go, client/status/object.go, client/status/object_test.go, client/status/session.go, client/status/v2.go, client/status/v2_test.go, object/lock.go, object/type.go, object/type_test.go
* based on and blocked by https://github.com/nspcc-dev/neofs-api-go/pull/371
=> object: Support `LOCK` type

client/accounting.go, client/common.go, client/container.go, client/netmap.go, client/object_delete.go, client/object_get.go, client/object_hash.go, client/object_put.go, client/object_search.go, client/reputation.go, client/session.go
Add `WithXHeaders` method to all `Client` operations.
=> client: Support request X-Headers

pool/pool.go
=> [#159] Add object context to session tokens

accounting/decimal.go, accounting/decimal_test.go, accounting/doc.go, accounting/test/decimal.go, accounting/test/doc.go, audit/doc.go, audit/result.go, audit/result_test.go, audit/test/doc.go, audit/test/generate.go, client/accounting.go
Remaining packages are going to be done in separate PRs.
=> Refactor and document API packages

go.mod, pool/pool.go
=> [#191] pool: use bearer token

client/common.go, client/response.go, client/session.go, pool/cache.go, pool/cache_test.go, pool/pool.go, pool/pool_test.go
Should be used along with https://github.com/nspcc-dev/neofs-node/issues/1189
Blocked by https://github.com/nspcc-dev/neofs-node/issues/1191
closes #137
=> [#137] Expire session token locally

pool/pool.go
=> [#203] pool: fix PrmContainerDelete

pool/pool.go
=> [#206] pool: fix waitForContainerRemoved

pool/pool.go
=> [#205] pool: fix using default key for requests

object/splitinfo.go, object/splitinfo_test.go
Close #242 .
Also write more tests.
=> object: require only 1 field to be set for `SplitInfo`

netmap/context.go, netmap/filter.go, netmap/filter_test.go, netmap/netmap.go, netmap/selector.go, netmap/selector_test.go
Close #229.
It isn't used anywhere outside of the package.
=> [#229] netmap: make context private

client/session.go, pool/pool.go
Related to https://github.com/nspcc-dev/neofs-s3-gw/issues/460
=> [#255] Create a session token using an arbitrary key

go.mod, go.sum
=> Upgrade NeoFS API Go to v2.12.2

eacl/validator.go, eacl/validator_test.go
=> [#243] eacl: Return success flag in `CalculateAction`

eacl/filter.go, eacl/filter_test.go
=> eacl: allow lossless conversion of reserved filters

storagegroup/storagegroup.go, storagegroup/storagegroup_test.go
Related to https://github.com/nspcc-dev/neofs-node/issues/1225.
=> Feat/Add Object <-> SG converters

netmap/policy.go, netmap/policy_test.go
=> netmap: Add more encoding methods for `PlacementPolicy`

client/errors.go, client/errors_test.go, pool/pool.go, pool/pool_test.go
=> client: Support wrapped errors

object/id/address.go, object/id/address_test.go
Inspired by [neofs-cdn-edge-manager](https://github.com/nspcc-dev/neofs-cdn-edge-manager/) project.
=> oid: Add JSON encoding of `Address` type

README.md, client/accounting.go, client/container.go, client/netmap.go, client/object_delete.go, client/object_get.go, client/object_hash.go, client/reputation.go, client/session.go
=> client: Fix docs of resolving the failure statuses

client/object_get.go, client/object_hash.go, client/status/object.go, client/status/v2.go, client/status/v2_test.go
=> Feat/Support `OUT_OF_RANGE` error

go.mod, go.sum
=> go.mod: Update tzhash to v1.6.0

go.mod, go.sum
=> go.mod: Update tzhash to v1.6.1

ns/nns.go, ns/nns_test.go
Related to https://github.com/nspcc-dev/neofs-s3-gw/pull/614 and https://github.com/nspcc-dev/neofs-http-gw/pull/178
=> [#301] ns: Adopt neo-go int parameter

pool/pool.go
Based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/296
close #291
=> [#291] Improve pool docs

client/container.go, client/errors.go, client/errors_test.go, client/status/container.go, client/status/v2.go, client/status/v2_test.go, go.mod, go.sum
=> Feat/Support EACL_NOT_FOUND status code

go.mod, go.sum
=> go.mod: Update neofs-api-go

client/object_delete.go, client/object_get.go, client/object_hash.go
=> client: provide pointers requests for signing

client/client.go
=> client: allow to set timeout for streaming operations

client/object_get.go
=> client: use parameter key in object.Get

netmap/node_info.go, netmap/node_info_test.go
=> netmap: support `ExternalAddr` well-known attribute

client/client.go
=> client: Use `context.Background` in `Dial` by default

crypto/util.go, netmap/node_info.go
Closes https://github.com/nspcc-dev/neofs-node/issues/1765
Signed-off-by: Anton Nikiforov <an.nikiforov@yadro.com>
=> Add StringifyPublicKey method for NodeInfo

pool/pool.go
=> [#364] pool: Adopt client stream timeout param

client/object_hash.go
=> client: allow to override key in Object.Hash RPC

pool/pool.go
=> [#365] pool: Add request callback

accounting/decimal.go, accounting/decimal_test.go, netmap/network_info.go, netmap/network_info_test.go, version/version.go, version/version_test.go
_Inspired by https://github.com/AxLabs/neofs-shared-lib project._
=> Add some encoding methods

pool/mock_test.go, pool/pool.go
=> Method to take raw client

object/search.go, object/search_test.go
=> filter: Add payload and homomorphic hash filter methods

client/example_container_put_test.go
=> documentation: Container create and get example

.github/CODEOWNERS
Let me have this green button.
=> .github: hey, I'm the code owner too!

eacl/enums.go, eacl/enums_test.go, eacl/record.go, eacl/record_test.go, object/search.go, object/search_test.go, object/type.go, object/type_test.go, storagegroup/storagegroup.go
=> Remove FromString method of enumerations

client/container.go, container/container.go, container/container_test.go, crypto/signer.go
=> Set external signer for requests payload

client/object_put.go, object/object.go, object/slicer/doc.go, object/slicer/options.go, object/slicer/slicer.go, object/slicer/slicer_test.go
* closes #342
For completion, I need to think about how to associate static slicing with client PUT.
=> Provide static object slicer

client/container.go, client/container_test.go, client/doc.go, client/errors.go, client/example_container_put_test.go, pool/mock_test.go, pool/pool.go
=> Mandatory action parameters in container operations

client/container.go, client/example_container_put_test.go, container/container.go, container/container_test.go, container/id/id.go, container/network.go, container/network_test.go, pool/pool.go
=> move methods to container

client/object_delete.go, client/object_get.go, client/object_get_test.go, client/object_hash.go, client/object_put.go, client/object_search.go, pool/accounting.go, pool/container.go, pool/netmap.go, pool/object.go, pool/pool.go, pool/pool_aio_test.go, pool/pool_test.go, pool/sampler_test.go, pool/session.go
=> Sync pool and client interfaces

pool/accounting.go, pool/container.go, pool/mock_test.go, pool/netmap.go, pool/object.go, pool/pool.go, pool/pool_aio_test.go, pool/pool_test.go, pool/session.go
=> Add statistic for new pool methods

client/object_delete.go, client/object_get.go, client/object_hash.go, client/object_put.go, client/object_search.go, pool/object.go, pool/pool_aio_test.go, pool/session.go, waiter/container_delete.go, waiter/container_eacl.go, waiter/container_put.go, waiter/doc.go, waiter/example_waiter_test.go, waiter/waiter.go
=> Waiter for Client and Pool

pool/example_pool_test.go, pool/pool.go, pool/pool_aio_test.go
=> Easier way to configure a pool

pool/cache.go, pool/cache_test.go, pool/mock_test.go, pool/pool.go, pool/pool_aio_test.go, pool/sampler_test.go, pool/session.go
=> Optimize session creation

client/object_get.go, object/slicer/slicer.go, object/slicer/slicer_test.go, pool/mock_test.go, pool/pool.go, pool/pool_aio_test.go, user/signer.go
=> Pre rc10 fixes

.golangci.yml, client/netmap.go, client/object_get.go, client/object_hash.go, client/session.go, pool/mock_test.go, pool/object.go, pool/pool.go, pool/pool_aio_test.go, pool/pool_test.go
=> Drop deprecated pool apis

checksum/example_test.go, client/object_search.go, client/object_search_test.go
=> Update ObjectListReader.Read function interface

.github/workflows/dco.yml
=> workflows: reuse DCO check from org repo

crypto/signer.go
Make it easier to understand, fix some misconceptions (hash/signature), use doc links (hi, #409).
=> crypto: improve StaticSigner documentation

audit/result.go, bearer/bearer.go, client/response.go, client/session.go, crypto/util.go, eacl/target.go, eacl/types.go, netmap/node_info.go, reputation/peer.go
=> Update documentation for public key using

bearer/bearer.go, bearer/bearer_test.go, container/container.go, crypto/test/tests.go, eacl/table.go, netmap/selector.go, object/fmt.go, object/fmt_test.go, reputation/test/generate.go, reputation/trust.go, reputation/trust_test.go, session/container.go, session/container_test.go, session/object.go, session/object_test.go
closes #510
Added func to known places with `Sign` method, plus for some places when I think it would be useful.
Of course, in some way it is almost similar to `Marshal` func, but for consistency called it _SignedData_.
If I missed any place, just mention it
=> Add SignedData func

pool/pool_aio_test.go
https://github.com/nspcc-dev/neofs-aio/pull/76 is needed as well for green.
=> Fix AIO tests

eacl/enums.go, eacl/enums_test.go, eacl/record.go, object/link.go, object/link_test.go, object/lock.go, object/lock_test.go, object/object.go, object/search.go, object/search_test.go, object/slicer/slicer_test.go, object/splitinfo.go, object/splitinfo_test.go, object/tombstone.go, object/tombstone_test.go, object/type.go, object/type_test.go, object/util_test.go
the pkg is big. Can be merged in parts. Say a stop word if that's enough
=> object: Improve testing and increase coverage

client/client.go, client/client_test.go
needed for SN connection manager rework https://github.com/nspcc-dev/neofs-node/issues/3229
=> client: Provide constructor from gRPC connection

client/object_search.go, proto/object/service.pb.go
Follow https://github.com/nspcc-dev/neofs-node/pull/3331.
=> client: Change SearchV2 response check for filtered attribute-less case

object/object.go, session/common.go, session/object.go, session/object_test.go
Refs https://github.com/nspcc-dev/neofs-node/issues/3359.
=> session: enhance token handling with version of object support
