nspcc-dev/neofs-sdk-go

pkg/pool/pool.go

pkg/pool/pool.go:86:32   staticcheck  SA1019: token.SessionToken is deprecated: use session.Token instead
pkg/pool/pool.go:92:16   staticcheck  SA1019: token.SessionToken is deprecated: use session.Token instead
pkg/pool/pool.go:151:46  staticcheck  SA1019: token.SessionToken is deprecated: use session.Token instead
Signed-off-by: Roman Khimov <roman@nspcc.ru>

pool: don't use deprecated token.SessionToken

---

pkg/pool/pool.go

Moved WithSession with session token got from pool.Connection
to the top of returned slice because it overlaps WithSession in
'option' parameter
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>

Change order of CallOptions in return of pool.conn

---

pool/pool.go

Since we transformed the pool of gRPC connection into the pool of neofs clients (see https://github.com/nspcc-dev/neofs-sdk-go/commit/10284ddd63ae734b191a2faad592c199b31660c8#), we don't need to call `EndpointInfo` to fetch the address of the node for the beautiful error output.
Moreover it is done incorrectly, because `c.CreateSession` may return `context.Cancelled` error (graceful shutdown). We will reuse the same context for the `EndpointInfo` call which will lead to a timeout freeze.

pool: Do not invoke EndpointInfo to find the address

---

go.mod
owner/id.go
owner/id_test.go
owner/test/id.go
owner/wallet.go

Also remove neofs-crypto dependency and use neo-go public key type
instead of `ecdsa.PublicKey`.

owner: move owner types from neofs-api-go

---

container/id/id.go
container/id/id_test.go
container/id/test/id.go
go.mod

Change `Marshal` signature to `Marshal() ([]byte, error)`.
Dependency update in SDK itself should be done after moving client
as `pool` package has some dependent function signatures.

container: move id from neofs-api-go

---

checksum/checksum.go
checksum/checksum_test.go
signature/signature.go
signature/signature_test.go
version/version.go
version/version_test.go

`xheader` will be moved with session package.

Move pkg/ structures from neofs-api-go

---

client/accounting.go
client/client.go
client/container.go
client/netmap.go
client/object.go
client/object_test.go
client/opts.go
client/raw.go
client/reputation.go
client/response.go
client/session.go
pool/mock_test.go
pool/pool.go
pool/pool_test.go
pool/sampler_test.go

`rpc` is still in `neofs-api-go`, I think it belongs there.

Move client package from neofs-api-go

---

netmap/node_info.go
netmap/selector.go
netmap/selector_test.go

If weights for some buckets are equal, result depends on the
initial positions of buckets in slice.
Props to @ZhangTao1596.

netmap: sort buckets before applying HRW

---

acl/types.go

- New non-final ACL constants for which eACL can be set
- Changed comments
Signed-off-by: Elizaveta Chichindaeva <elizaveta@nspcc.ru>

Add ACL constants to acl/types.go

---

client/opts.go
go.mod
go.sum

In the latest NeoFS protocol update, each request is provided with a
network magic number. We have to provide the ability to set it on
the client.
Add `WithNetworkMagic` option constructor which accepts magic number.
Write the number to meta header of the all requests.

client: Configure network magic

---

netmap/json_tests/many_selects.json

Move `PlacementPolicy_ProcessSelectors` test. It tests how good
nodes were grouped into buckets after selection, but we can still query
full results and check them.

Add one more JSON test

---

client/container.go
pool/pool.go

PutContainer method takes `container.Container` structure as an argument. This structure already contains session token field, so there is no need in `prmSession` because it duplicates session token definition.
In current version, `client` ignores session token from `container.Container` structure completely.

client: Don't accept session token params in PutContainer

---

pool/pool.go
pool/pool_test.go

```
$ grep -I -r 'SessionExpirationEpoch' ./ 
./neofs-sftp-gw/main.go:                SessionExpirationEpoch:  math.MaxUint64,
./neofs-s3-gw/cmd/authmate/main.go:             SessionExpirationEpoch: math.MaxUint32,
./neofs-s3-gw/cmd/s3-gw/app.go:         SessionExpirationEpoch:  math.MaxUint64,
./restic/internal/backend/neofs/util.go:                SessionExpirationEpoch:  cfg.SessionExpiration,
./neofs-http-gw/app.go:         SessionExpirationEpoch:  math.MaxUint64,
./neofs-http-gw/integration_test.go:            SessionExpirationEpoch: math.MaxUint64,
```
I think it is bad to encourage developers to create infinite session tokens. To solve it I propose to specify duration in epochs and calculate absolute value directly in the pool.
---
Two more things to discuss:
1. External apps tend …

Replace session token expiration value with expiration duration

---

pool/cache.go
pool/cache_test.go
pool/pool.go

Closes #126 
In this PR I am trying to solve an issue when session token is invalid at `pool.PutObject()` execution. It can happen because: 
- remote storage node was restarted and all session tokens are gone,
- session token has been expired. 
Pool takes care of session token management, so it should not ignore and throw this type of errors. In other requests, pool can do a resend. `pool.PutObject()` on the other hand operates with object payload, which can be presented in a form of a stream (see NeoFS HTTP Gateway). Pool can't read payload stream twice (right now it does read it twice and produces objects with empty payload as it stated in #126). Therefore solution should remove request resend from `pool.PutObject()` and provide a way to reinitialize session token in case of an errors. …

Do not resend object.Put requests in pool

---

client/common.go
client/object_delete.go
client/object_get.go
pool/pool.go

We should provide the ability to customize private of object HEAD /
DELETE ops.
Implement `UseKey` method on `PrmObjectHead` / `PrmObjectDelete` types.
Sign requests with the specified key if called.

client: Customize private key in object HEAD/DELETE

---

go.mod
go.sum
session/session.go
session/session_test.go

Use new types instead of the deprecated ones.

Upgrade to NeoFS API Go v2.12.0

---

client/container.go
object/fmt.go
reputation/trust.go
session/session.go
signature/signature.go
token/bearer.go
util/signature/data.go
util/signature/options.go

Allow `SignOption` to set 2 parameters:
1. Default signature scheme, which is used in case scheme is
unspecified.
2. Restrict scheme option which also checks that scheme is either
unspecified or equal to the restricted scheme. This is only used
for verification and is necessary because some of the signatures
are used in smart-contracts.
Also provide signature struct to sign/verify functions in helpers.

signature: Add scheme

---

client/object_search.go
client/object_search_test.go
pool/pool.go

Limiting iteration number can be easily achieved on the caller side, not sure if we need a public function for this.

[#148] client: Allow to iterate over search results

---

go.mod
go.sum
signature/signature.go
util/signature/data.go
util/signature/options.go

`SignData`: use `ECDSAWithSHA512` by default. `SignWithRFC6979` option
switches the scheme to `RFC6979WithSHA256`.
`VerifyData`: if scheme is not fixed (like by `SignWithRFC6979` option)
then scheme from the message is processed.

signature: Change scheme selection

---

client/client.go

Balance request should be replaced with more generic Dial() call from neofs-api-go.

Do not return rpc.Balance error in Dial

---

eacl/filter.go
eacl/record.go
eacl/table.go
eacl/target.go
eacl/test/benchmark_test.go
pool/pool.go
pool/pool_test.go
version/version.go

Using `EqualTo` is faster than binary comparison (scenario: waiting eacl presence). When we have unmarshaled eacl table (that's true for `waitForEACLPresence`) it's easier to compare by records rather than marshal and compare in binary form.
Suffix numbers in benchmark names are lengths records, filters, targets in table.
```
BenchmarkTableBinaryComparison
BenchmarkTableBinaryComparison-16        	  289216	      4000 ns/op
BenchmarkTableEqualToComparison
BenchmarkTableEqualToComparison-16       	11110905	       102.5 ns/op
BenchmarkTableBinaryComparison10
BenchmarkTableBinaryComparison10-16      	    6127	    182411 ns/op
BenchmarkTableEqualToComparison10
BenchmarkTableEqualToComparison10-16     	  238905	      5073 ns/op
BenchmarkTableBinaryComparison100 …
```

[#180] eacl: add EqualTo

---

object/object.go
storagegroup/doc.go
storagegroup/storagegroup.go
storagegroup/storagegroup_test.go
storagegroup/test/doc.go
storagegroup/test/generate.go

Blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/200.

Refactor/Refactor and document the `storagegroup` package

---

client/object_put.go

Object service of NeoFS API contains one client-side stream method: object.Put. In client-side streams, server can return an error after processing stream message. In this case write method returns `io.EOF` and actual error reason is encoded in response status, which is obtained after `Close()`. Client library should process such case.
Related https://github.com/nspcc-dev/neofs-node/issues/1315

client: Decode status at io.EOF in the client-side stream

---

client/container.go

Container contract expects signature of container ID value, which is SHA256 of container body. Not the signature of stable
marshaled container.ID structure.

client: Sign container ID value at container removal

---

session/container.go
session/container_test.go

Required in S3 Gateway to [differentiate](https://github.com/nspcc-dev/neofs-s3-gw/blob/ea8e1b3b1987910602c2557855f173fdec8bb089/api/layer/layer.go#L634) `ErrBucketAlreadyOwnedByYou` and `ErrBucketAlreadyExists` errors.
Can be simple `Owner()` getter method, I suppose, but `session` package mostly have sugared methods in `Container`, so I did the same.

session: Add `container.IssuedBy` method

---

session/container.go
session/container_test.go

There is a need to duplicate session token owner, e.g. in container
created within the session.

session: Add `CopyIssuer` method of `Container`

---

session/object.go
session/object_test.go

Add method to get `Object` session's issuer similar to `Container`.

session: Add `Object.Issuer` method

---

client/common.go

In previous implementation `processResponse` returned `true` if
`resolveAPIFailures` is set and status failure is received. This led to
post-processing of the results, which no longer pays attention to the
status. For example, `ObjectHead` returned `unexpected header type`
error due to empty body.
Make `contextCall.processResponse` to return success flag regardless of
`resolveAPIFailures` setting. Make `contextCall.processCall` to return
`err` field presence flag on `processResponse` false return.

client: Fix incorrect response processing case

---

container/id/id_test.go
eacl/filter.go
eacl/record.go
eacl/record_test.go
eacl/test/benchmark_test.go
ns/nns_test.go
object/id/id_test.go
object/search.go
object/search_test.go

Use `EncodeToString` method to get protocol string according to type
docs.

Fix string encoding of identifiers

---

eacl/table.go

Container ID of extended ACL table can be omitted in bearer token according
to API.
Signed-off-by: Pavel Karpy <carpawell@nspcc.ru>
Closes #235.

Fix/Do not require CID in eACL table

---

session/common.go
session/container.go
session/container_test.go
session/object.go
session/object_test.go

`Container` and `Object` types are transmitted in single `session.Token`
message. They differ only by session context.
Share common parts of the message in `commonData` struct. Embed struct
into `Container` and `Object`. Make `ReadFromV2` methods to check
protocol compliance. Make `Unmarshal`/`UmarshalJSON` to check field
format in case of presence only.
* closes #235

session: Share common code between `Container` and `Object`

---

session/container.go
session/container_test.go

There is a need to verify session data signatures calculated using
private session key. `Container` token encapsulates public session key,
so we need to provide method for signature check.

session: Implement method to verify session data signature

---

storagegroup/storagegroup.go
storagegroup/storagegroup_test.go

It panicked when the previous members slice had capacity more than a new one
because of incorrect slicing that led to `out of range`.
Signed-off-by: Pavel Karpy <carpawell@nspcc.ru>

Fix/SG's `out of range`

---

client/object_put.go

After 85e3c7b0870693fe025c5c46cabfb583d2bb5811 `processResponse` method
sets `err` field or sets status in `statusRes` field of `contextCall`.
In previous implementation `ObjectWriter.Close` method returned
`ctxCall.err` on `false` return of `processResponse` method. This could
cause NPE-panic if status failure resolving was disabled.
Make `ObjectWriter.Close` to return internal `err` field only if it is
set, otherwise return status response.
* issue for test coverage #270

client: Fix response processing of Object.Put rpc

---

client/container.go
container/container.go
container/container_test.go
eacl/table.go
eacl/table_test.go
pool/pool.go

Session token and signature isn't presented in `Container` and
`EACLTable` messages of NeoFS API V2 protocol. These entities are needed
for access control and doesn't carry payload of these messages.
Remove `SetSessionToken` / `SessionToken` methods of
`container.Container` and `eacl.Table` types. Provide methods to specify
these components in corresponding `Client` operations.

container: Remove session token and signature from Container/eACL

---

crypto/crypto_test.go
crypto/ecdsa/init.go
crypto/ecdsa/wallet_connect.go
crypto/signer.go
go.mod
go.sum

Blocked by https://github.com/nspcc-dev/neofs-api-go/pull/386
Related #155 .

util/signature: add WalletConnect API support

---

netmap/network_info.go
netmap/network_info_decode_test.go

NEO VM uses little-endian format for integers,
however the resulting byte slice can contain less than 8 bytes.

netmap: allow more uint64 config values

---

netmap/policy.go
netmap/policy_test.go

In previous implementation `PlacementPolicy.DecodeString` produced
undesired console logs.
* closes #280

policy: Remove error listeners from query lexer

---

accounting/decimal.go
accounting/decimal_test.go
bearer/bearer.go
checksum/checksum.go
client/accounting.go
client/netmap.go
container/container_test.go
crypto/crypto_test.go
crypto/signature.go
object/fmt.go
object/object.go
reputation/trust.go
session/common.go
session/container.go
storagegroup/storagegroup.go
storagegroup/storagegroup_test.go
version/version.go

Return `error` from all `ReadFromV2` methods in order to support
backward compatibility if message will be extended with some formatted
field.
* closes #284
All linter remarks are linked with an issue and will be fixed within it.

[#284] *: Return error from all `ReadFromV2` methods

---

client/accounting.go
client/common.go
client/container.go
client/errors.go
client/netmap.go
client/object_delete.go
client/object_hash.go
client/object_put.go
pool/pool.go
pool/pool_test.go

In previous implementation `client` package provided access to nested
response fields as pointers to them. This caused clients to handle nil
cases even when the field presence in the response is required.
Avoid returning pointers to required fields in response getters. This
also reduces reference counter load and allows fields to be decoded
directly without additional assignment.
* closes #299
I decided to not make changes compatible and just change the return type.

client: Do not use pointers to required response fields

---

client/object_put.go

In previous implementation `ObjectWrite.Close` called `close` method
which in turn called `result` callback. Thus failed statuses could lead
to false-positive result processing.
Replace calling `close` method with direct `closer` method's call in
`ObjectWrite.Close` directly.
* closes #317

client: Fix processing of the Object PUT failed response

---

pool/mock_test.go
pool/pool.go
pool/sampler_test.go

In previous implementation `pool` package provided access to resulting
values as pointers to them. This caused clients to handle nil
cases even when the field presence in the response is required.
Avoid returning pointers to values in result getters. This also reduces
reference counter load and allows values from `client.Client` to be
forwarded directly without additional assignment.
* prolongs #299

pool: Do not use pointers to the resulting values

---

client/object_put.go

Fix #320 .
@cthulhu-rider could you tell a bit more about the commit message? It seems like `close` calls `closer` and returns the error, what was the problem?
This reverts commit f8148c954bf26d2f228b9ec16282d80b062328f8.
Anyway, let's merge this to fix `neofs-cli object put` on master an fix the issue later.

Fix object put

---

client/common.go
client/container.go
client/object_delete.go
client/object_get.go
client/object_hash.go
client/object_put.go
client/object_search.go
client/object_search_test.go
client/session.go
pool/pool.go

It is nice to have all control-flow in a single file (ideally, on a single screen). In this PR we get rid of using multiple callbacks in object* methods. The result uses less code and is simpler to follow IMO.

Simplify object client methods

---

client/status/common.go
client/status/v2.go
client/status/v2_test.go

* relates #315
We previously forgot to do this in https://github.com/nspcc-dev/neofs-sdk-go/pull/335. I've left an issue to prevent this in future https://github.com/nspcc-dev/neofs-sdk-go/issues/340.

Decode `MAINTENANCE` error from status messages

---

client/api.go
client/client.go
client/client_test.go
client/netmap.go
client/netmap_test.go
go.mod
go.sum
netmap/netmap.go
netmap/netmap_test.go
netmap/test/generate.go

Extend functionality of `NetMap` type. Add `NetMapSnapshot` operation to `client` package.
* based on and blocked by https://github.com/nspcc-dev/neofs-api-go/pull/418

netmap: Support `NetmapService.NetmapSnapshot` RPC

---

go.mod
go.sum
pool/pool.go
session/object.go
session/object_test.go
session/test/session.go

Rename `LimitByObject` method of the `session.Object` type to `LimitByObjects` and make it to accept variadic parameter.
* based on and blocked by https://github.com/nspcc-dev/neofs-api-go/pull/416

session: Support group object sessions

---

client/client.go
client/client_test.go
go.mod
go.sum
pool/pool.go
pool/pool_test.go

* based on and blocked by https://github.com/nspcc-dev/neofs-api-go/pull/419
* closes #343

client: Accept context parameter in `Dial`

---

pool/mock_test.go
pool/pool.go
pool/pool_test.go
pool/sampler_test.go

[#358] pool: Start even if not all node healthy

---

object/relations/doc.go
object/relations/relations.go
pool/pool.go

**Note:** we collect phy objects only if session doesn't provided by client. Besides if user doesn't have right to HEAD/SEARCH object (e.g. restricted rules in bearer token) the removal will fail also.
Include phy objects in session token scope
close #360 

[#360] pool: Fix removing virtual object

---

pool/pool.go

Similar to https://github.com/nspcc-dev/neofs-node/pull/2196
Problem:
During removing big object pool finds all small parts to form a valid session token. 
This leads to [using `raw` flag](https://github.com/nspcc-dev/neofs-sdk-go/blob/170f31b7c45469565a1dd0990d65484f6f686068/pool/pool.go#L2539) and getting `SplitErrorInfo` in built-in error (not in status). Such errors increase [error counter](https://github.com/nspcc-dev/neofs-sdk-go/blob/170f31b7c45469565a1dd0990d65484f6f686068/pool/pool.go#L987) and after 100 (default value) such errors connection to this node marks as `unhealthy`.

[#374] pool: Fix handling SplitInfoError

---

pool/pool.go
pool/pool_test.go

[#362] pool: Don't use default session token for read

---

client/api.go
client/errors.go
client/netmap_test.go
client/session.go
client/session_test.go

Set contextCall.err if missed session params

---

object/object.go
storagegroup/storagegroup.go

If we can return a bool signifying field presence, then it can be used this way as well. Refs. #226.

object/sg: improve error handling in some ReadFromV2 cases

---

client/accounting.go
client/container.go
client/example_container_put_test.go
client/netmap.go
client/netmap_test.go
client/object_delete.go
client/object_hash.go
client/object_put.go
pool/pool.go

We've got a number of `Res*` things with a single member only. They were somewhat useful before #413 (to get request status), but now they provide zero value and just complicate the code using these APIs. Notice also that this makes `client` interface a little close to `pool` interface which is nice wrt. #380.

Strip useless res structs

---

pool/pool.go

The logic with container set was broken after [this commit ](https://github.com/nspcc-dev/neofs-sdk-go/commit/22ac6f536da1e441e56c1500da9f2631b34951c3#diff-7dc553983ffc8155d2dc76de139b8b581f7d7161d2b640d59e62d5c499c23c12L1995)

Use container in pools objectDelete

---

object/fmt.go
object/fmt_test.go
object/lock.go
object/lock_test.go
object/object.go
object/object_test.go
object/slicer/slicer.go
object/slicer/slicer_test.go

Move object operations to Object structure

---

client/object_delete.go
client/object_get.go
client/object_hash.go
client/object_put.go
client/object_search.go
client/session_container.go
pool/doc.go
pool/example_pool_test.go
pool/object.go
pool/session.go

Describe pool session management

---

object/slicer/slicer.go
object/slicer/slicer_test.go

Added split info to the first child

---

client/container.go
client/netmap.go
pool/pool.go

Deduplicate client and pool SyncContainerWithNetwork logic

---

object/slicer/slicer.go
object/slicer/slicer_test.go

Split ID relates to split-chain only, original root object should not carry this information, otherwise, it will be perceived by the system itself as part of a sliced chain that does not exist.

slicer: Do not write split ID into parent header

---

client/container_statistic_test.go
client/object_put.go
object/object.go
object/slicer/options.go
object/slicer/slicer.go
object/slicer/slicer_test.go
pool/object.go
pool/pool.go
pool/pool_aio_test.go
pool/pool_test.go

Make Slicer interface more generic

---

client/container_statistic_test.go
client/example_container_put_test.go
crypto/signature.go
crypto/signature_test.go
crypto/signer.go
crypto/test/tests.go
crypto/util.go
crypto/util_test.go
object/slicer/slicer_test.go
pool/example_pool_test.go
pool/pool.go
session/common.go
session/container_test.go
session/object_test.go
user/signer.go
waiter/example_waiter_test.go

* track adaptations in https://github.com/nspcc-dev/neofs-node/pull/2449

Extend package API with features usefule for existing apps

---

object/slicer/slicer.go
object/slicer/slicer_test.go

The case when the reader returns io.EOF with the last data chunk. Slicer was closing the writer without payload writing

Fix slicer upload in some cases

---

audit/collect.go
client/object_get.go
object/relations/relations.go
pool/mock_test.go
pool/object.go
pool/pool.go
pool/pool_aio_test.go

Return header directly instead of wrapper struct

---

client/container_statistic_test.go
client/object_put.go
client/object_put_test.go

If EOF is returned on `Write` call, close the stream, try to unwrap status and return it immediately as `error` instead of direct `io.EOF`. Closes #496.

fix/Do not return EOF while streaming payload

---

pool/cache.go
pool/pool.go
pool/pool_aio_test.go

Update session control inside pool

---

audit/result.go
bearer/bearer.go
checksum/checksum.go
client/response.go
client/session.go
crypto/signature.go
crypto/signer.go
eacl/record.go
eacl/table.go
eacl/target.go
netmap/netmap.go
netmap/network_info.go
netmap/node_info.go
object/attribute.go
object/object.go
object/range.go
object/splitinfo.go
object/tombstone.go
reputation/peer.go
stat/statistic.go
user/id.go

Marked method which returning value must not be changed, because it leads to data malfunction. Left as is places where we create a new var and return it by pointer. Such var mutation is safe for our structs.
closes #187

Document mutability of reference types

---

container/container.go
container/container_internal_test.go
eacl/filter.go
eacl/filter_test.go
eacl/record.go
eacl/record_test.go
eacl/table.go
eacl/table_internal_test.go
eacl/target.go
eacl/target_test.go
netmap/policy.go
netmap/policy_internal_test.go
object/object.go
object/object_copy.go
object/object_internal_test.go
session/common.go
session/common_test.go
session/container.go
session/container_internal_test.go
session/object.go
session/object_internal_test.go

Add CopyTo method for deep copy

---

client/object_get.go
client/object_put.go
client/object_search.go
pool/pool.go

Replaces #519, fixes #518 and #520.

Fix stream statistics and pool restarts

---

netmap/example_test.go
netmap/node_info.go
netmap/node_info_test.go

_Inspired by https://github.com/nspcc-dev/neofs-node/issues/2280_

netmap: Extend `NodeInfo` type with verified nodes' domain

---

netmap/network_info_test.go
netmap/policy_test.go
object/attribute.go
object/attribute_test.go
object/test/generate.go
user/id_test.go

I don't have the strength to keep this to myself anymore.

Add Parameterized constructor to the attribute

---

pool/pool_aio_test.go

After recent changes, NeoFS AIO Docker container deploys NeoFS chain (deploy contracts, initial transfers, etc.) from scratch internally. This takes around 60 blocks (`~1m`), so AIO takes more than 1 minute to run. Previous test timeout `45s` was insufficient in practice, causing the test to fail.
Timeout is increased to `2m`. The value is still pretty short, at the same time, failure to succeed within this duration will require an individual review for problems.

pool: Increase timeout to start NeoFS AIO Docker container for testing

---

client/client_test.go
client/common.go
client/object_replicate.go
client/object_replicate_test.go
go.mod
go.sum

* _inspired by https://github.com/nspcc-dev/neofs-node/issues/2317_

client: Add `ReplicateObject` method

---

go.mod
go.sum
object/search.go
object/search_test.go

* based on and blocked by https://github.com/nspcc-dev/neofs-api/pull/285

object: Support numerical matchers in search queries

---

object/object.go
object/search.go

* based on and blocked by https://github.com/nspcc-dev/neofs-api/issues/279

object: Purge notification functionality

---

object/slicer/slicer.go
object/slicer/slicer_test.go

Another header == object cool thing.

slicer: Do not drop link object's payload

---

object/slicer/slicer.go
object/slicer/slicer_test.go

Since link objects have payload now, they may overflow max regular object size. Client-size error is better that server-side overflow message. Not expected in practice but may be observed when running some extreme local installations for tests (e.g., 1K limit and 100K object).

slicer: Do not put link objects that will be rejected

---

bearer/bearer.go
bearer/bearer_test.go
bearer/example_test.go
go.mod
go.sum
object/slicer/slicer.go
session/common.go
session/container.go
session/container_test.go
session/object.go
session/object_test.go

* based on and blocked by https://github.com/nspcc-dev/neofs-api-go/pull/446

Token signatures and issuers

---

object/search.go
object/search_test.go

This field appeared for V2 split first and was not required at first glance. More use cases have been landed now. Also, it is a successor to the SplitID in the V1 split that does have a filter.
API go repo is accepted for archival so no additional const importing for now, will be fixed somehow with removing `neofs-api-go` from go.mod.

object/filters: Add filtering by first object ID

---

bearer/bearer.go
bearer/bearer_test.go
client/container_statistic_test.go
container/container_internal_test.go
container/example_test.go
eacl/filter.go
eacl/filter_test.go
eacl/record.go
eacl/record_test.go
netmap/helper_test.go
netmap/policy.go
netmap/policy_internal_test.go
netmap/policy_test.go
netmap/selector_test.go
netmap/test/generate.go
pool/pool_aio_test.go
session/container.go
session/container_test.go
session/object.go
session/object_test.go
waiter/example_waiter_test.go

https://github.com/nspcc-dev/neo-go/ imports indirectly, all fine. https://github.com/nspcc-dev/neofs-node is maintained in a bundle and can be cleaned up last (not in this PR)
projects:
* https://github.com/nspcc-dev/neofs-rest-gw/
* https://github.com/nspcc-dev/neofs-s3-gw

Free apps from using `github.com/nspcc-dev/neofs-api-go/v2` module

---

pool/pool_aio_test.go

now it builds, but my local run failed with `TestPoolAio/nspccdev/neofs-aio:latest: failed to start container`

pool: Fix AIO test

---

client/common.go

It appears if passing more then one attribute to the command

Fix out of range panic

---

internal/proto/encoding.go
internal/proto/encoding_test.go

#583 became a fat sketch. Starting from this, changes will come partially leaving code ambiguity while facilitating review

Add functionality for Protocol Buffers stable marshaling

---

session/test/session.go

Chronology was broken for lifetime values (created already expired).

session/test: "generate" valid session tokens

---

eacl/target.go
eacl/target_test.go
eacl/types.go
eacl/validator.go
eacl/validator_test.go
user/id.go

Refs https://github.com/nspcc-dev/neofs-api/issues/278

Account based eacl targets

---

netmap/context.go
netmap/netmap.go
netmap/selector.go

It can be a problem to distinguish this error in cases when it is not a real problem (e.g., checking if a node belongs to a container).

netmap: export `ErrNotEnoughNodes`

---

.github/workflows/tests.yml

Sometimes merged code != PR code and we want to have some proper statistics for covertage as well (it doesn't have proper data for master now because we're not collecting it).

workflows: run tests for master

---

accounting/decimal_test.go
netmap/netmap_test.go
netmap/network_info.go
netmap/network_info_test.go
netmap/node_info.go
netmap/node_info_test.go
netmap/policy_test.go

netmap: Improve testing and increase coverage

---

bearer/bearer.go
bearer/bearer_test.go
eacl/table.go
session/common.go
session/common_test.go
session/container_test.go
session/object_test.go
version/version_test.go

bearer: Improvements and test coverage

---

.github/workflows/tests.yml

Deprecated, to be removed.
https://github.com/actions/runner-images/issues/10721

workflows: drop macos-12 runner

---

object/slicer/slicer.go

Root ID is only set for the last object which always have the same rootIDHandler defined. Intermediate objects don't pass true into last, so this callback doesn't make much sense.

slicer: optimize out rootIDHandler

---

pool/pool.go
pool/sampler.go
pool/sampler_test.go

we can also just mutex the panicking part, safe `rand` functions do the same

pool: Fix unsafe randomizers

---

crypto/proto.go

1. This is wrong by definition.
2. We only need a very small subset of it here in fact.

crypto: do not rely on internal proto.Message for public interfaces

---

client/object_search.go

It is required for testing purposes.

Add count getter for SearchObjectsOptions

---

client/client.go

DialContext calls NewClient and it's specified to perform no I/O at all, so we don't know whether the node is alive or not. We're querying network info from it to ensure it's OK, but this request uses parent context, so it takes some unknown time instead of a proper dial timeout.

client: make Dial follow the timeout parameter

---

client/client.go
client/client_test.go

It's too easy to make this mistake, so it's easier to simplify requirements here. Fixes #705.

client: do not panic on Close() of uninited connection

---

object/slicer/slicer.go

* caught while testing https://github.com/nspcc-dev/neofs-node/pull/3305

object/slicer: Do not override object owner with bearer token issuer

---

client/common.go

NewBuffer() implies some pooled buffers and DefaultBufferPool is exactly that -- the default pool where buffers are put after use. This means that any given slice of data will end up there and then could be reused for any other gRPC-related purpose. This is not something users of client package can expect, so unexpected memory corruptions are quite possible.
Regression of b7f8cd08340176bd9f58fe030e137d29fd627201.

client: fix incorrect gRPC buffer pool use

---

eacl/types.go
eacl/validator.go
eacl/validator_test.go

This allows for lazy header fetching.

eacl: make it possible to return error from HeadersOfType()

---

client/object_get.go
client/object_get_test.go
proto/netmap/types.pb.go
proto/object/service.pb.go

* based on and blocked by https://github.com/nspcc-dev/neofs-api/pull/334

Support unsigned object GET/HEAD responses
